In [1]:
from gym_match3.envs import Match3Env
import gym
import matplotlib.pyplot as plt
# import pickle
from matplotlib import style
import numpy as np
#from gym_match3.envs.levels import Match3Levels, Level
env = Match3Env()
obs, reward, done, info = env.step(0) 
import torch
import cv2
from PIL import Image

In [14]:
8*14

112

In [12]:
a = torch.randn(5,3)

print(a)
torch.argmax(a).item()

tensor([[ 0.5082,  0.2091, -0.6589],
        [ 0.4368, -0.9282, -1.4083],
        [ 0.2311, -1.3703,  0.2485],
        [ 0.5776, -0.6714,  0.9488],
        [ 0.5705,  0.5920,  0.0077]])


11

In [12]:
[np.arange(0, 10), torch.argmax(a, axis=1)]

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([0, 0, 2, 2, 1, 0, 0, 0, 0, 2])]

In [18]:
a = torch.randn(4, 4)

print(a)

torch.argmax(a).item()

tensor([[-0.1893, -0.8176,  0.5331,  0.5208],
        [-0.0175,  0.8905,  0.5617,  1.2580],
        [-0.1224, -0.2451,  0.2909, -1.3044],
        [ 1.0577,  0.0864,  0.7516,  0.4662]])


7

In [ ]:
#env = Match3Env() 
#env.observation_space
#env.get_available_actions()   #查看action對應的動作

In [8]:
def plot_obs(observation=None):
    
    d = {0: (255, 255, 255),   #白色
     1: (0, 255, 255),      #黃色
     2: (0, 0, 255) ,      #紅色
     3: (230,224,176) ,   #灰藍色 
     4: (0,0,0)}           #黑色    
    
    
    background = np.zeros((8,8,3), dtype=np.uint8) #黑色的背景

    for color in range(5):
        result = np.where(observation == color)
        
        listOfCoordinates= list(zip(result[1], result[2]))
        
        for cord in listOfCoordinates:
            background[cord] = d[color]     
            
    img = Image.fromarray(background, 'RGB')
     
    
    #img = img.resize((500, 800)) 
    cv2.imshow("image", np.array(img))
    
    cv2.waitKey(200)

In [9]:

env = Match3Env()
obs, reward, done, info = env.step(36) 
#plot_obs(obs)

list(enumerate(env.get_available_actions()))

NameError: name 'Image' is not defined

In [6]:
def one_hot_encoding(obs):
    
    obs = obs.reshape(8,8).astype(int)
    
    grid_onehot = np.zeros(shape=(5, 8, 8))
    table = {i:i for i in range(0,5)}
    
    for i in range(8):
        for j in range(8):
            grid_element = obs[i][j]
            grid_onehot[table[grid_element]][i][j]=1
            
    return grid_onehot

In [2]:
def plot_obs(observation=None):
    
    d = {0: (255, 255, 255),   #白色
     1: (0, 255, 255),      #黃色
     2: (0, 0, 255) ,      #紅色
     3: (230,224,176) ,   #灰藍色 
     4: (0,0,0)}           #黑色    
    
    
    background = np.zeros((8,8,3), dtype=np.uint8) #黑色的背景

    for color in range(5):
        result = np.where(one_hot_encoding(obs)[color] == 1)
        
        listOfCoordinates= list(zip(result[0], result[1]))
        
        for cord in listOfCoordinates:
            background[cord] = d[color]     
            
    img = Image.fromarray(background, 'RGB')
     
    
    #img = img.resize((500, 800)) 
    cv2.imshow("image", np.array(img))
    
    cv2.waitKey(200)

In [56]:
plot_obs(obs)

In [3]:
env = Match3Env()

In [26]:
env.observation_space
env.get_available_actions()[36]

frozenset({(3, 4), (3, 5)})

In [50]:

obs, reward, done, info = env.step(36) 
print(obs)

one_hot_encoding(obs)

[[[0. 0. 2. 3. 0. 1. 0. 4.]
  [1. 2. 1. 2. 4. 1. 2. 3.]
  [2. 4. 3. 0. 3. 2. 3. 3.]
  [3. 1. 1. 0. 1. 0. 3. 0.]
  [1. 3. 3. 4. 2. 4. 4. 1.]
  [2. 0. 2. 3. 4. 1. 2. 3.]
  [2. 4. 3. 2. 1. 2. 1. 0.]
  [1. 1. 0. 0. 1. 2. 1. 2.]]]


array([[[1., 1., 0., 0., 1., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 1., 1., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 1., 0., 0.],
        [1., 0., 1., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0., 1., 0.],
        [1., 1., 0., 0., 1., 0., 1., 0.]],

       [[0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [1., 0., 1., 0., 0., 0., 1., 0.],
        [1., 0., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1

In [198]:
print(obs)
temp2 = one_hot_encoding(obs)
print(temp2.shape)


[[[4 3 4 1 3 2 4 3]
  [2 2 0 3 2 3 0 1]
  [3 1 2 2 3 4 1 3]
  [2 1 2 3 4 1 2 1]
  [3 4 3 4 4 1 3 4]
  [0 0 1 0 0 3 2 1]
  [3 1 0 2 3 0 4 2]
  [0 3 0 2 1 3 0 0]]]
(5, 8, 8)


In [164]:
grid_onehot = np.zeros(shape=(5, 8, 8))

for i in obs:
    for j in i:
        


#grid_onehot[0]

SyntaxError: unexpected EOF while parsing (<ipython-input-164-09774013aa23>, line 8)

In [11]:
from gym_match3.envs import Match3Env
import gym
from PIL import Image
import cv2
import numpy as np
   


env = Match3Env() 
for i_episode in range(2): #玩一次遊戲

    
    for t in range(10):  #做10個 action
        
        action = env.action_space.sample()
        
        print('---------------')

        
        observation, reward, done, info = env.step(action)
 
        print(observation.shape)

        #plot_obs(observation)
        
        print('the swap of coordinate is: ',list(env.get_available_actions()[action]))
        #print('reward:', reward)
        print(t)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

---------------
(1, 8, 8)
the swap of coordinate is:  [(2, 7), (1, 7)]
0
---------------
(1, 8, 8)
the swap of coordinate is:  [(7, 4), (7, 5)]
1
---------------
(1, 8, 8)
the swap of coordinate is:  [(1, 5), (2, 5)]
2
---------------
(1, 8, 8)
the swap of coordinate is:  [(2, 6), (3, 6)]
3
---------------
(1, 8, 8)
the swap of coordinate is:  [(3, 0), (4, 0)]
4
---------------
(1, 8, 8)
the swap of coordinate is:  [(6, 3), (6, 2)]
5
---------------
(1, 8, 8)
the swap of coordinate is:  [(2, 0), (2, 1)]
6
---------------
(1, 8, 8)
the swap of coordinate is:  [(3, 4), (2, 4)]
7
---------------
(1, 8, 8)
the swap of coordinate is:  [(4, 6), (3, 6)]
8
---------------
(1, 8, 8)
the swap of coordinate is:  [(0, 7), (1, 7)]
9
---------------
(1, 8, 8)
the swap of coordinate is:  [(3, 4), (3, 3)]
0
---------------
(1, 8, 8)
the swap of coordinate is:  [(5, 6), (5, 7)]
1
---------------
(1, 8, 8)
the swap of coordinate is:  [(4, 5), (3, 5)]
2
---------------
(1, 8, 8)
the swap of coordinate is