In [1]:
from gym_match3.envs import Match3Env
import gym
import matplotlib.pyplot as plt

from matplotlib import style
import numpy as np

env = Match3Env()
#obs, reward, done, info = env.step(0) 
import torch
import cv2

from PIL import Image

from gym_match3.envs.levels import LEVELS #  default levels
from gym_match3.envs.levels import Match3Levels, Level


from gym_match3.envs.game import (Board,
                                  RandomBoard,
                                  CustomBoard,
                                  Point,
                                  Cell,
                                  AbstractSearcher,
                                  MatchesSearcher)


from gym_match3.envs.game import OutOfBoardError, ImmovableShapeError

In [2]:
def one_hot_encoding(obs):
    
    obs = obs.reshape(obs.shape[1],obs.shape[2]).astype(int)
    
    grid_onehot = np.zeros(shape=(env.n_shapes, obs.shape[0], obs.shape[1]))
    table = {i:i for i in range(0,10)}
    
    for i in range(obs.shape[0]):
        for j in range(obs.shape[1]):
            grid_element = obs[i][j]
            grid_onehot[table[grid_element]][i][j]=1
            
    return grid_onehot



def plot_obs(observation=None):
    
    d = {0: (255, 255, 255),   #白色
     1: (0, 255, 255),      #黃色
     2: (0, 0, 255) ,      #紅色
     3: (230,224,176) ,   #灰藍色 
     4: (0,0,0), #黑色  
     5: (100,100,100),
        6:(150,150,150),
        7:(200,200,200),
        8:(200,150,250),
        9:(250,200,150),
        10:(150,200,250)}              
    
    
    background = np.zeros((observation.shape[1],observation.shape[2],3), dtype=np.uint8) #黑色的背景

    for color in range(env.n_shapes):
        result = np.where(one_hot_encoding(observation)[color] == 1)
        
        listOfCoordinates= list(zip(result[0], result[1]))
        
        for cord in listOfCoordinates:
            background[cord] = d[color]     
            
    img = Image.fromarray(background, 'RGB')
     
    
    #img = img.resize((500, 800)) 
    cv2.imshow("image", np.array(img))
    
    cv2.waitKey(200)
    
    
    
def Getlevels(WidthAndHeight,shapes):
    LEVELS = [Level(WidthAndHeight,WidthAndHeight,shapes, np.zeros((WidthAndHeight,WidthAndHeight)).tolist())]
    return LEVELS

env = Match3Env(levels=Match3Levels(Getlevels(4,6)))

In [6]:
from gym_match3.envs import Match3Env
import gym
from PIL import Image
import cv2
import numpy as np
from random import choice


env = Match3Env(levels=Match3Levels(Getlevels(6,10)))



available_actions = {v : k for k, v in dict(enumerate(env.get_available_actions())).items()}



for i_episode in range(1): #玩 1次遊戲
     
    observation = env.reset() 
    
    while True:
        
        #plot_obs(observation)  #畫圖
        print(observation)    
        validate_move = env.possible_move   # 一般用 env 的屬性紀錄合法走步
        
        
        
        #一開始遊戲初始化時,env的屬性會是 None,以及重新一場遊戲時要再 get一次合法走步
        if validate_move == None or len(validate_move)== 0:  
      
            validate_move = env.get_validate_actions()
        
        print(validate_move)
        
        validate_list = []       
        for i in validate_move:
            if i in available_actions:
                validate_list.append(available_actions.get(i))   
         

        action = choice(validate_list)
        
        
        observation, reward, done, info = env.step(action)  # step函數會檢查下一個 observation 有沒有合法走步,並回傳 observation,如果沒有合法走步 done == True
            
        
        print('the swap of coordinate is: ',list(env.get_available_actions()[action]))

        if done:           
            break


[[[7. 3. 0. 5. 5. 6.]
  [7. 8. 0. 0. 6. 3.]
  [9. 4. 1. 8. 3. 5.]
  [3. 9. 9. 8. 7. 2.]
  [3. 0. 6. 1. 4. 9.]
  [2. 4. 8. 1. 6. 8.]]]
[((2, 0), (3, 0))]
the swap of coordinate is:  [(2, 0), (3, 0)]
[[[0. 7. 4. 5. 5. 6.]
  [7. 3. 9. 0. 6. 3.]
  [7. 8. 7. 8. 3. 5.]
  [3. 4. 1. 8. 7. 2.]
  [3. 0. 6. 1. 4. 9.]
  [2. 4. 8. 1. 6. 8.]]]
[((0, 0), (0, 1)), ((3, 2), (3, 3))]
the swap of coordinate is:  [(0, 0), (0, 1)]
[[[0. 0. 4. 5. 5. 6.]
  [3. 3. 9. 0. 6. 3.]
  [9. 8. 7. 8. 3. 5.]
  [3. 4. 1. 8. 7. 2.]
  [3. 0. 6. 1. 4. 9.]
  [2. 4. 8. 1. 6. 8.]]]
[((1, 0), (2, 0)), ((3, 2), (3, 3))]
the swap of coordinate is:  [(1, 0), (2, 0)]
[[[7. 0. 4. 5. 5. 6.]
  [7. 3. 9. 0. 6. 3.]
  [1. 8. 7. 8. 3. 5.]
  [0. 4. 1. 8. 7. 2.]
  [9. 0. 6. 1. 4. 9.]
  [2. 4. 8. 1. 6. 8.]]]
[((3, 2), (3, 3))]
the swap of coordinate is:  [(3, 2), (3, 3)]
[[[7. 0. 4. 4. 5. 6.]
  [7. 3. 9. 0. 6. 3.]
  [1. 8. 7. 8. 3. 5.]
  [0. 4. 8. 5. 7. 2.]
  [9. 0. 6. 0. 4. 9.]
  [2. 4. 8. 8. 6. 8.]]]
[((5, 4), (5, 5)), ((2, 2), (3, 2))]
t