In [1]:
from gym_match3.envs import Match3Env
import gym
import matplotlib.pyplot as plt

from matplotlib import style
import numpy as np

env = Match3Env()
#obs, reward, done, info = env.step(0) 
import torch
import cv2

from PIL import Image

from gym_match3.envs.levels import LEVELS #  default levels
from gym_match3.envs.levels import Match3Levels, Level


from gym_match3.envs.game import (Board,
                                  RandomBoard,
                                  CustomBoard,
                                  Point,
                                  Cell,
                                  AbstractSearcher,
                                  MatchesSearcher)


from gym_match3.envs.game import OutOfBoardError, ImmovableShapeError

def one_hot_encoding(obs):
    
    obs = obs.reshape(obs.shape[1],obs.shape[2]).astype(int)
    
    grid_onehot = np.zeros(shape=(env.n_shapes, obs.shape[0], obs.shape[1]))
    table = {i:i for i in range(-1,10)}
    
    for i in range(obs.shape[0]):
        for j in range(obs.shape[1]):
            grid_element = obs[i][j]
            grid_onehot[table[grid_element]][i][j]=1
            
    return grid_onehot



    
    
def Getlevels(WidthAndHeight,shapes):
    LEVELS = [Level(WidthAndHeight,WidthAndHeight,shapes, np.zeros((WidthAndHeight,WidthAndHeight)).tolist())]
    return LEVELS




[2. 3. 1. 4. 1. 1. 0. 3.]
[ 4.  2. nan  4.  3.  0.  1.  3.]
new_line [0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 1
nans_mask [False False  True False False False False False]
[ 4.  2. nan  4.  3.  0.  1.  3.]
spec_mask [False False  True False False False False False]
regular_values [4. 2. 4. 3. 0. 1. 3.]
new_line2 [nan  4.  2.  4.  3.  0.  1.  3.]
[ 2.  4. nan  3.  2.  0.  1. nan]
new_line [0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 2
nans_mask [False False  True False False False False  True]
[ 2.  4. nan  3.  2.  0.  1. nan]
spec_mask [False False  True False False False False  True]
regular_values [2. 4. 3. 2. 0. 1.]
new_line2 [nan nan  2.  4.  3.  2.  0.  1.]
[ 0.  3. nan  1.  1.  2.  3. nan]
new_line [0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 2
nans_mask [False False  True False False False False  True]
[ 0.  3. nan  1.  1.  2.  3. nan]
spec_mask [False False  True False False False False  True]
regular_values [0. 3. 1. 1. 2. 3.]
new_line2 [nan nan  0.  3.  1.  1.  2.  3.]
[ 3.  0.  4.  4.  1.  4

In [13]:
available_actions = {v : k for k, v in dict(enumerate(env.get_available_actions())).items()}
print(available_actions)

{((0, 0), (1, 0)): 0, ((0, 1), (1, 1)): 1, ((0, 2), (1, 2)): 2, ((0, 3), (1, 3)): 3, ((0, 4), (1, 4)): 4, ((1, 0), (2, 0)): 5, ((1, 1), (2, 1)): 6, ((1, 2), (2, 2)): 7, ((1, 3), (2, 3)): 8, ((1, 4), (2, 4)): 9, ((2, 0), (3, 0)): 10, ((2, 1), (3, 1)): 11, ((2, 2), (3, 2)): 12, ((2, 3), (3, 3)): 13, ((2, 4), (3, 4)): 14, ((3, 0), (4, 0)): 15, ((3, 1), (4, 1)): 16, ((3, 2), (4, 2)): 17, ((3, 3), (4, 3)): 18, ((3, 4), (4, 4)): 19, ((0, 0), (0, 1)): 20, ((0, 1), (0, 2)): 21, ((0, 2), (0, 3)): 22, ((0, 3), (0, 4)): 23, ((1, 0), (1, 1)): 24, ((1, 1), (1, 2)): 25, ((1, 2), (1, 3)): 26, ((1, 3), (1, 4)): 27, ((2, 0), (2, 1)): 28, ((2, 1), (2, 2)): 29, ((2, 2), (2, 3)): 30, ((2, 3), (2, 4)): 31, ((3, 0), (3, 1)): 32, ((3, 1), (3, 2)): 33, ((3, 2), (3, 3)): 34, ((3, 3), (3, 4)): 35, ((4, 0), (4, 1)): 36, ((4, 1), (4, 2)): 37, ((4, 2), (4, 3)): 38, ((4, 3), (4, 4)): 39}


In [12]:
observation = env.reset() 
print(observation)
print(env.get_validate_actions())


[[[1. 2. 0. 3. 4.]
  [1. 1. 2. 4. 4.]
  [3. 0. 3. 0. 3.]
  [1. 3. 0. 3. 2.]
  [1. 1. 3. 2. 2.]]]
[((1, 0), (2, 0)), ((3, 2), (3, 3)), ((2, 3), (3, 3)), ((3, 1), (3, 2)), ((2, 1), (3, 1)), ((3, 2), (4, 2)), ((2, 2), (3, 2)), ((2, 0), (3, 0))]


In [14]:
observation, reward, done, info = env.step(action = 12)
print(done)
print(observation)
print(env.get_validate_actions())

new_line [0. 0. 0. 0. 0.]
num_of_nans 2
immov_mask [False False False False False]
nans_mask [False False  True  True False]
new_line [0. 0. 0. 0. 0.]
num_of_nans 2
immov_mask [False False False False False]
nans_mask [False False  True  True False]
new_line [0. 0. 0. 0. 0.]
num_of_nans 2
immov_mask [False False False False False]
nans_mask [False False  True  True False]
False
[[[ 1.  1.  4. -1.  4.]
  [ 1.  0. -1. -1.  4.]
  [ 3.  2.  0.  3.  3.]
  [ 1.  1.  2.  4.  2.]
  [ 1.  1.  3.  2.  2.]]]
[((1, 0), (2, 0)), ((2, 0), (3, 0)), ((3, 3), (4, 3)), ((3, 2), (4, 2))]


In [15]:
observation, reward, done, info = env.step(action = 17)
print(done)
print(observation)
print(env.get_validate_actions())


new_line [ 0. -1.  0.  0.  0.]
num_of_nans 1
immov_mask [False  True False False False]
nans_mask [False False False False  True]
new_line [-1. -1.  0.  0.  0.]
num_of_nans 1
immov_mask [ True  True False False False]
nans_mask [False False False False  True]
new_line [0. 0. 0. 0. 0.]
num_of_nans 1
immov_mask [False False False False False]
nans_mask [False False False False  True]
False
[[[ 1.  1. -1. -1. -1.]
  [ 1.  0. -1. -1.  4.]
  [ 3.  2.  4. -1.  4.]
  [ 1.  1.  0.  3.  3.]
  [ 1.  1.  3.  4.  2.]]]
[((1, 0), (2, 0)), ((2, 0), (3, 0)), ((3, 2), (4, 2))]


In [17]:
observation, reward, done, info = env.step(action = 5)
print(done)
print(observation)
print(env.get_validate_actions())


new_line [0. 0. 0. 0. 0.]
num_of_nans 3
immov_mask [False False False False False]
nans_mask [False False  True  True  True]
False
[[[-1.  1. -1. -1. -1.]
  [-1.  0. -1. -1.  3.]
  [-1.  2.  1. -1.  4.]
  [ 1.  1.  4.  1.  4.]
  [ 3.  1.  0.  4.  2.]]]
[((3, 2), (3, 3)), ((2, 2), (3, 2)), ((4, 3), (4, 4)), ((3, 3), (4, 3)), ((2, 1), (2, 2))]


In [6]:
observation, reward, done, info = env.step(action = 36)
print(observation)
print(env.get_validate_actions())

[nan  4.  1.  0.  3.  0.  4.  2.]

[nan  1.  4.  3.  0.  2.  1.  2.]

[nan  4.  2.  1.  3.  4.  1.  1.]

[nan  4.  1.  1.  3.  2.  4.  0.]

[[[ 3.  3.  1. -1.  4.  3.  0.  4.]
  [ 1.  3.  4.  1.  4.  4.  3.  0.]
  [ 4.  2.  1.  4.  2.  1.  0.  3.]
  [ 3.  2.  0.  3.  1.  1.  0.  2.]
  [ 1.  0.  3.  0.  3.  3.  4.  2.]
  [ 1.  3.  0.  2.  4.  2.  2.  3.]
  [ 2.  3.  4.  1.  1.  4.  3.  1.]
  [ 2.  1.  2.  2.  1.  0.  2.  1.]]]
[((4, 2), (5, 2)), ((4, 2), (4, 3)), ((1, 2), (1, 3)), ((4, 7), (5, 7)), ((3, 2), (4, 2)), ((4, 1), (4, 2)), ((3, 3), (4, 3)), ((7, 0), (7, 1)), ((1, 3), (2, 3)), ((5, 3), (5, 4)), ((0, 6), (1, 6)), ((2, 3), (2, 4)), ((5, 6), (5, 7)), ((1, 6), (1, 7))]


In [7]:
observation, reward, done, info = env.step(action = 27)
print(observation)
print(env.get_validate_actions())

[nan  1.  4.  1.  0.  0.  4.  2.]

[-1. nan  1.  4.  0.  2.  1.  2.]

[nan  4.  4.  2.  1.  4.  1.  1.]

[nan  3.  4.  1.  1.  2.  4.  0.]

[nan  3.  3.  2.  2.  3.  3.  1.]

[-1. nan  1.  4.  1.  0.  4.  2.]

[-1. nan  1.  1.  4.  2.  1.  2.]

[nan nan nan  2.  1.  4.  1.  1.]

[[[ 3.  0. -1. -1.  3.  4.  0.  4.]
  [ 1.  3.  2. -1.  4.  3.  3.  0.]
  [ 4.  3.  1.  1.  4.  4.  0.  3.]
  [ 3.  2.  4.  1.  2.  1.  0.  2.]
  [ 1.  2.  1.  4.  1.  1.  4.  2.]
  [ 1.  3.  0.  2.  4.  2.  2.  3.]
  [ 2.  3.  4.  1.  1.  4.  3.  1.]
  [ 2.  1.  2.  2.  1.  0.  2.  1.]]]
[((4, 2), (4, 3)), ((5, 6), (5, 7)), ((0, 4), (0, 5)), ((0, 4), (1, 4)), ((3, 4), (4, 4)), ((0, 0), (0, 1)), ((4, 7), (5, 7)), ((4, 3), (4, 4)), ((3, 3), (4, 3)), ((7, 0), (7, 1)), ((3, 2), (3, 3)), ((1, 7), (2, 7)), ((1, 4), (1, 5)), ((5, 3), (5, 4)), ((0, 6), (1, 6)), ((4, 4), (5, 4)), ((3, 0), (3, 1)), ((1, 6), (1, 7))]


In [40]:
observation, reward, done, info = env.step(action = 15)
print(observation)
print(env.get_validate_actions())

[[[ 2. -1. -1.  4.]
  [ 2.  1.  1.  3.]
  [ 1.  0.  4.  0.]
  [ 3.  4.  3.  0.]]]
[((1, 0), (2, 0))]


In [41]:
observation, reward, done, info = env.step(action = 4)
print(observation)
print(env.get_validate_actions())

[[[-1. -1. -1.  4.]
  [ 2.  0.  0.  3.]
  [ 2.  0.  4.  0.]
  [ 3.  4.  3.  0.]]]
[((1, 3), (2, 3)), ((1, 2), (1, 3)), ((1, 2), (2, 2))]


In [2]:
from gym_match3.envs import Match3Env
import gym
from PIL import Image
import cv2
import numpy as np
from random import choice


env = Match3Env(levels=Match3Levels(Getlevels(10,5)))



available_actions = {v : k for k, v in dict(enumerate(env.get_available_actions())).items()}



for i_episode in range(1): #玩 1次遊戲
     
    observation = env.reset() 
    
    while True:
        env.render()
       
        validate_move = env.possible_move   # 一般用 env 的屬性紀錄合法走步
        
        
        
        #一開始遊戲初始化時,env的屬性會是 None,以及重新一場遊戲時要再 get一次合法走步
        if validate_move == None or len(validate_move)== 0:  
      
            validate_move = env.get_validate_actions()
        
        #print(validate_move)
        
        validate_list = []       
        for i in validate_move:
            if i in available_actions:
                validate_list.append(available_actions.get(i))   
         

        action = choice(validate_list)
        
        
        observation, reward, done, info = env.step(action)  # step函數會檢查下一個 observation 有沒有合法走步,並回傳 observation,如果沒有合法走步 done == True
            
        
        print('the swap of coordinate is: ',list(env.get_available_actions()[action]))

        if done:           
            break


[4. 3. 0. 3. 3. 0. 4. 2. 3. 1.]
[1. 1. 2. 2. 3. 0. 2. 4. 4. 2.]
[ 3. nan nan nan  2.  1.  1.  0.  3.  1.]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 3
nans_mask [False  True  True  True False False False False False False]
[ 3. nan nan nan  2.  1.  1.  0.  3.  1.]
spec_mask [False  True  True  True False False False False False False]
regular_values [3. 2. 1. 1. 0. 3. 1.]
new_line2 [nan nan nan  3.  2.  1.  1.  0.  3.  1.]
[nan nan nan  4.  2.  3.  2.  4.  1.  3.]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 3
nans_mask [ True  True  True False False False False False False False]
[nan nan nan  4.  2.  3.  2.  4.  1.  3.]
spec_mask [ True  True  True False False False False False False False]
regular_values [4. 2. 3. 2. 4. 1. 3.]
new_line2 [nan nan nan  4.  2.  3.  2.  4.  1.  3.]
[2. 4. 1. 0. 1. 0. 0. 2. 2. 1.]
[3. 4. 0. 0. 2. 0. 2. 3. 4. 3.]
[2. 3. 1. 1. 0. 4. 2. 4. 4. 1.]
[0. 3. 3. 0. 4. 0. 0. 3. 2. 3.]
[0. 4. 0. 4. 0. 2. 2. 0. 1. 0.]
[2. 2. 3. 4. 3. 1. 0. 0. 2. 2.

[3. 1. 2. 1. 4. 1. 3. 4. 4. 3.]
[ 2.  3. nan  2.  3.  0.  2.  2.  4.  2.]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 1
nans_mask [False False  True False False False False False False False]
[ 2.  3. nan  2.  3.  0.  2.  2.  4.  2.]
spec_mask [False False  True False False False False False False False]
regular_values [2. 3. 2. 3. 0. 2. 2. 4. 2.]
new_line2 [nan  2.  3.  2.  3.  0.  2.  2.  4.  2.]
[ 0.  3. nan  3.  3.  0.  1.  4.  2.  3.]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 1
nans_mask [False False  True False False False False False False False]
[ 0.  3. nan  3.  3.  0.  1.  4.  2.  3.]
spec_mask [False False  True False False False False False False False]
regular_values [0. 3. 3. 3. 0. 1. 4. 2. 3.]
new_line2 [nan  0.  3.  3.  3.  0.  1.  4.  2.  3.]
[ 3.  4. nan  2.  4.  2.  4.  3.  2.  0.]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 1
nans_mask [False False  True False False False False False False False]
[ 3.  4. nan  2.  4.  2.  4.  3.  2.  0.]

the swap of coordinate is:  [(6, 4), (7, 4)]
[2. 3. 1. 2. 1. 4. 1. 3. 4. 3.]
[3. 1. 4. 3. 0. 0. 3. 0. 4. 2.]
[0. 4. 4. 0. 0. 1. 0. 1. 2. 3.]
[2. 1. 2. 2. 1. 2. 2. 3. 2. 0.]
[ 2.  4.  0. nan nan nan  3.  0.  0.  1.]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 3
nans_mask [False False False  True  True  True False False False False]
[ 2.  4.  0. nan nan nan  3.  0.  0.  1.]
spec_mask [False False False  True  True  True False False False False]
regular_values [2. 4. 0. 3. 0. 0. 1.]
new_line2 [nan nan nan  2.  4.  0.  3.  0.  0.  1.]
[1. 3. 0. 4. 1. 1. 3. 2. 1. 0.]
[2. 0. 2. 1. 4. 0. 1. 3. 3. 0.]
[3. 1. 4. 2. 2. 4. 3. 0. 4. 3.]
[2. 4. 1. 4. 2. 0. 4. 4. 0. 0.]
[1. 2. 2. 3. 0. 1. 3. 1. 0. 2.]
the swap of coordinate is:  [(5, 4), (5, 5)]
[2. 3. 1. 2. 1. 4. 1. 3. 4. 3.]
[3. 1. 4. 3. 0. 0. 3. 0. 4. 2.]
[0. 4. 4. 0. 0. 1. 0. 1. 2. 3.]
[ 2.  1.  2.  2.  1.  2.  2.  3.  2. nan]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 1
nans_mask [False False False False False False False Fal

the swap of coordinate is:  [(3, 8), (4, 8)]
[2. 3. 1. 2. 1. 4. 1. 3. 4. 3.]
[3. 3. 1. 4. 3. 0. 0. 3. 0. 4.]
[1. 0. 4. 4. 0. 0. 1. 0. 1. 3.]
[0. 3. 2. 1. 2. 2. 1. 2. 2. 3.]
[2. 2. 4. 3. 2. 4. 0. 3. 0. 1.]
[3. 1. 3. 0. 4. 1. 1. 3. 2. 1.]
[0. 4. 2. 0. 1. 4. 0. 1. 3. 3.]
[ 0.  3.  1.  4.  2.  4.  3.  4. nan  3.]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 1
nans_mask [False False False False False False False False  True False]
[ 0.  3.  1.  4.  2.  4.  3.  4. nan  3.]
spec_mask [False False False False False False False False  True False]
regular_values [0. 3. 1. 4. 2. 4. 3. 4. 3.]
new_line2 [nan  0.  3.  1.  4.  2.  4.  3.  4.  3.]
[ 3.  2.  4.  1.  4.  0.  4.  4. nan  0.]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 1
nans_mask [False False False False False False False False  True False]
[ 3.  2.  4.  1.  4.  0.  4.  4. nan  0.]
spec_mask [False False False False False False False False  True False]
regular_values [3. 2. 4. 1. 4. 0. 4. 4. 0.]
new_line2 [nan  3.  2.  4

the swap of coordinate is:  [(3, 2), (3, 3)]
[0. 2. 3. 2. 1. 4. 1. 3. 4. 4.]
[ 2.  3.  3.  4.  3.  0.  0.  3.  0. nan]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 1
nans_mask [False False False False False False False False False  True]
[ 2.  3.  3.  4.  3.  0.  0.  3.  0. nan]
spec_mask [False False False False False False False False False  True]
regular_values [2. 3. 3. 4. 3. 0. 0. 3. 0.]
new_line2 [nan  2.  3.  3.  4.  3.  0.  0.  3.  0.]
[ 4.  2.  1.  0.  0.  4.  1.  0.  1. nan]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 1
nans_mask [False False False False False False False False False  True]
[ 4.  2.  1.  0.  0.  4.  1.  0.  1. nan]
spec_mask [False False False False False False False False False  True]
regular_values [4. 2. 1. 0. 0. 4. 1. 0. 1.]
new_line2 [nan  4.  2.  1.  0.  0.  4.  1.  0.  1.]
[-1.  3.  2.  4.  3.  1.  1.  2.  2. nan]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 1
nans_mask [False False False False False False False False False  Tr

the swap of coordinate is:  [(4, 7), (4, 8)]
[0. 2. 3. 2. 1. 4. 1. 3. 4. 4.]
[nan  2.  3.  3.  4.  3.  4.  0.  3.  0.]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 1
nans_mask [ True False False False False False False False False False]
[nan  2.  3.  3.  4.  3.  4.  0.  3.  0.]
spec_mask [ True False False False False False False False False False]
regular_values [2. 3. 3. 4. 3. 4. 0. 3. 0.]
new_line2 [nan  2.  3.  3.  4.  3.  4.  0.  3.  0.]
[nan nan nan nan nan nan nan  4.  2.  0.]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 7
nans_mask [ True  True  True  True  True  True  True False False False]
[nan nan nan nan nan nan nan  4.  2.  0.]
spec_mask [ True  True  True  True  True  True  True False False False]
regular_values [4. 2. 0.]
new_line2 [nan nan nan nan nan nan nan  4.  2.  0.]
[-1.  3.  2.  4.  3.  1.  1.  2.  2. nan]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 1
nans_mask [False False False False False False False False False  True]
[-1.  3.  2.  

the swap of coordinate is:  [(5, 0), (5, 1)]
[0. 2. 3. 2. 1. 3. 1. 3. 4. 4.]
[nan nan nan nan  2. nan nan nan  0.  0.]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 7
nans_mask [ True  True  True  True False  True  True  True False False]
[nan nan nan nan  2. nan nan nan  0.  0.]
spec_mask [ True  True  True  True False  True  True  True False False]
regular_values [2. 0. 0.]
new_line2 [nan nan nan nan nan nan nan  2.  0.  0.]
[nan nan nan nan nan nan nan nan  4.  0.]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 8
nans_mask [ True  True  True  True  True  True  True  True False False]
[nan nan nan nan nan nan nan nan  4.  0.]
spec_mask [ True  True  True  True  True  True  True  True False False]
regular_values [4. 0.]
new_line2 [nan nan nan nan nan nan nan nan  4.  0.]
[-1.  3.  4.  4.  3.  1.  1.  2. nan nan]
new_line [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_of_nans 2
nans_mask [False False False False False False False False  True  True]
[-1.  3.  4.  4.  3.  1.  1.  2. na

IndexError: Cannot choose from an empty sequence